#Copied from https://github.com/alexeagleson/docker-node-postgres-template#useful-docker-commands and modified
version: '3.8'
services:
    vue-front:
        build:
            context: front-end
        ports:
            - "80:80"
        volumes:
            - ./front-end/:/app

    app:
        build:
            context: back-end
        depends_on:
            # Our app does not work without our database
            # so this ensures our database is loaded first
            postgres_container:
                condition: service_healthy
        ports:
            - "8080:8080"
            - "5000:5000"
            - "9229:9229"
        volumes:
            # Maps our current project directory `.` to
            # our working directory in the container
            - ./back-end/:/usr/src/app/
            - /usr/src/app/node_modules
            - //var/run/docker.sock:/var/run/docker.sock

        #environment:
        #    - NODE_ENV=development
        #command:
        #    - nodemon

    # This is the configuration for our PostgreSQL database container
    # Note the `postgres_container` name is important, in out Node app when we refer
    # to  `host: "postgres_container"` that value is mapped on the network to the 
    # address of this container.
    postgres_container:
        image: postgres:14
        restart: always
        environment:
            # You can set the value of environment variables
            # in your docker-compose.yml file
            # Our Node app will use these to connect
            # to the database
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=root
        ports: #Enable for development / migrations
            - "5432:5432"
        volumes:
            # When the PostgresSQL container is started it will run any scripts
            # provided in the `docker-entrypoint-initdb.d` directory, this connects
            # our seed file to that directory so that it gets run
            - ./back-end/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U root"]
            interval: 5s
            timeout: 5s
            retries: 5

    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "haldur@mail.com"
            PGADMIN_DEFAULT_PASSWORD: "raskeparool"
        ports:
            - "16543:80"
        depends_on:
            - postgres_container