# Docker Compose example for running a MySQL database
services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terminal

    # Mount a volume to persist the data
    # Feel free to remove this if you don't need to persist the data after the container is removed
    volumes:
      - mysqldata:/var/lib/mysql

# Volume for persisting the data
# Feel free to remove this if you don't need to persist the data after the container is removed
volumes:
  mysqldata:
