catalogMode: prefer
cleanupUnusedCatalogs: true

shellEmulator: true
trustPolicy: no-downgrade

packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.4.2
  '@iconify-json/lucide': ^1.2.78
  '@kubernetes/client-node': ^1.4.0
  '@nuxt/eslint': ^1.11.0
  '@nuxt/image': ^2.0.0
  '@nuxt/test-utils': ^3.21.0
  '@nuxt/ui': ^4.2.1
  '@nuxtjs/i18n': ^10.2.1
  '@types/node': ^24.10.1
  '@types/ssh2': ^1.15.5
  '@vueuse/nuxt': ^14.1.0
  '@xterm/addon-fit': ^0.10.0
  '@xterm/xterm': ^5.5.0
  better-auth: ^1.4.5
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.44.7
  eslint: ^9.39.1
  eslint-plugin-turbo: ^2.6.3
  husky: ^9.1.7
  mysql2: ^3.15.3
  nuxt: ^4.2.1
  p-limit: ^7.2.0
  p-retry: ^7.1.0
  pino: ^10.1.0
  pino-pretty: ^13.1.3
  ssh2: ^1.17.0
  tailwindcss: ^4.1.17
  turbo: ^2.6.3
  typescript: ^5.9.3
  vue: ^3.5.25
  vue-router: ^4.6.3
  vue-tsc: ^3.1.5
  zod: ^4.1.13
