packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^6.2.0
  '@nuxt/eslint': ^1.10.0
  '@nuxt/image': ^2.0.0
  '@nuxt/test-utils': ^3.20.1
  '@nuxt/ui': ^4.1.0
  '@types/node': ^24.10.1
  eslint: ^9.39.1
  eslint-plugin-turbo: ^2.6.0
  husky: ^9.1.7
  nuxt: ^4.2.1
  tailwindcss: ^4.1.17
  turbo: ^2.6.1
  typescript: ^5.9.3
  vue: ^3.5.24
  vue-router: ^4.6.3
  vue-tsc: ^3.1.3
  zod: ^4.1.12
