catalogMode: prefer
cleanupUnusedCatalogs: true
injectWorkspacePackages: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^7.0.1
  '@azure/arm-containerinstance': ^9.1.0
  '@azure/communication-email': ^1.1.0
  '@azure/core-rest-pipeline': ^1.22.2
  '@azure/identity': ^4.13.0
  '@azure/keyvault-secrets': ^4.10.0
  '@iconify-json/flag': ^1.2.10
  '@iconify-json/lucide': ^1.2.85
  '@kubernetes/client-node': ^1.4.0
  '@nuxt/eslint': ^1.12.1
  '@nuxt/ui': ^4.3.0
  '@nuxtjs/i18n': ^10.2.1
  '@sindresorhus/slugify': ^3.0.0
  '@tsconfig/node-ts': ^23.6.2
  '@tsconfig/node24': ^24.0.3
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.10.4
  '@types/nodemailer': ^7.0.5
  '@types/sortablejs': ^1.15.9
  '@types/ssh2': ^1.15.5
  '@types/sshpk': ^1.17.4
  '@vueuse/nuxt': ^14.1.0
  '@xterm/addon-fit': ^0.11.0
  '@xterm/addon-webgl': ^0.19.0
  '@xterm/xterm': ^6.0.0
  better-auth: ^1.4.12
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  eslint: ^9.39.2
  eslint-plugin-turbo: ^2.7.4
  husky: ^9.1.7
  lodash-es: ^4.17.22
  mysql2: ^3.16.0
  nodemailer: ^7.0.2
  nuxt: ^4.2.2
  p-limit: ^7.2.0
  p-retry: ^7.1.1
  pino: ^10.2.0
  pino-pretty: ^13.1.3
  sortablejs: ^1.15.6
  ssh2: ^1.17.0
  sshpk: ^1.18.0
  tailwindcss: ^4.1.18
  turbo: ^2.7.4
  typescript: ^5.9.3
  vue: ^3.5.26
  vue-router: ^4.6.4
  vue-tsc: ^3.2.2
  zod: ^4.3.5
