catalogMode: strict
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade

# Force legacy deploy mode to avoid requiring injectWorkspacePackages=true.
# Without this, TypeScript fails to resolve workspace package types during 'pnpm install'
# because dist folders don't exist yet when packages are hard-linked to the store.
forceLegacyDeploy: true

packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^7.4.3
  '@aws-sdk/client-ec2': ^3.989.0
  '@aws-sdk/client-ecs': ^3.989.0
  '@aws-sdk/client-secrets-manager': ^3.989.0
  '@aws-sdk/client-sesv2': ^3.989.0
  '@azure/arm-containerinstance': ^9.1.0
  '@azure/communication-email': ^1.1.0
  '@azure/core-rest-pipeline': ^1.22.2
  '@azure/identity': ^4.13.0
  '@azure/keyvault-secrets': ^4.10.0
  '@iconify-json/flag': ^1.2.10
  '@iconify-json/lucide': ^1.2.90
  '@kubernetes/client-node': ^1.4.0
  '@nuxt/eslint': ^1.15.1
  '@nuxt/ui': ^4.4.0
  '@nuxtjs/i18n': ^10.2.3
  '@sindresorhus/slugify': ^3.0.0
  '@tsconfig/node-ts': ^23.6.3
  '@tsconfig/node24': ^24.0.4
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.10.13
  '@types/nodemailer': ^7.0.9
  '@types/sortablejs': ^1.15.9
  '@types/ssh2': ^1.15.5
  '@types/sshpk': ^1.17.4
  '@vueuse/nuxt': ^14.2.1
  '@xterm/addon-fit': ^0.11.0
  '@xterm/addon-webgl': ^0.19.0
  '@xterm/xterm': ^6.0.0
  better-auth: ^1.4.18
  drizzle-kit: ^0.31.9
  drizzle-orm: ^0.45.1
  eslint: ^9.39.2
  eslint-plugin-turbo: ^2.8.7
  husky: ^9.1.7
  lodash-es: ^4.17.23
  mysql2: ^3.17.1
  nodemailer: ^8.0.1
  nuxt: ^4.3.1
  p-limit: ^7.3.0
  p-retry: ^7.1.1
  pino: ^10.3.1
  pino-pretty: ^13.1.3
  sortablejs: ^1.15.7
  ssh2: ^1.17.0
  sshpk: ^1.18.0
  tailwindcss: ^4.1.18
  turbo: ^2.8.7
  typescript: ^5.9.3
  vue: ^3.5.28
  vue-router: ^4.6.4
  vue-tsc: ^3.2.4
  zod: ^4.3.6
