apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu
      image: ghcr.io/eistre/terminal-ubuntu
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /etc/.ssh
          name: ssh
          readOnly: true
      command:
        - '/bin/bash'
        - '-c'
        - |
          cat /etc/.ssh/id_rsa > /home/user/.ssh/authorized_keys && \
          chown -R user:user /home/user/.ssh && \
          chmod 700 /home/user/.ssh && \
          chmod 600 /home/user/.ssh/authorized_keys && \
          /usr/sbin/sshd -D
      resources:
        requests:
          memory: 64Mi
          cpu: 100m
        limits:
          memory: 128Mi
          cpu: 500m
  volumes:
    - name: ssh
      secret:
        secretName: ssh