name: Ubuntu image for Linux Terminal Application

on:
  push:
    paths:
      - './Dockerfile.ubuntu'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login --username eistre --password ${{ secrets.GHCR_TOKEN }} ghcr.io
      - name: Build the Ubuntu image
        run: docker build . --file Dockerfile.ubuntu --tag ghcr.io/eistre/terminal-ubuntu:latest
      - name: Push Ubuntu image
        if: github.ref == 'refs/heads/master'
        run: docker push ghcr.io/eistre/terminal-ubuntu:latest